/**
 * Webhook signature helpers (spec §8).
 *
 * NOTE: this module imports `node:crypto`. It is exported from
 * `@sendsprite/shared/node` only; the root barrel (and any browser bundle)
 * must not import it.
 */
import { createHmac, timingSafeEqual } from "node:crypto";
import { SIGNATURE_TOLERANCE_SECONDS } from "./webhooks";

const digest = (timestamp: number, body: string, secret: string) =>
  createHmac("sha256", secret).update(`${timestamp}.${body}`).digest("hex");

/**
 * `t=<unix seconds>,v1=<hex hmac-sha256 of "<t>.<body>">`. Always one `v1`;
 * the verifier accepts several so a future rotation can sign with both keys
 * without breaking receivers that are already deployed.
 */
export function signWebhook(
  body: string,
  secret: string,
  timestamp = Math.floor(Date.now() / 1000),
): string {
  // `createHmac("sha256", "")` is legal in Node, so an empty secret would
  // produce a well-formed header that every receiver rejects (the verifier
  // returns false on an empty secret) — a delivery that fails for a reason
  // nobody can see. A secret this side is always generated by `newSecret()`,
  // so an empty one is a bug: fail loudly where it is introduced.
  if (!secret) throw new Error("signWebhook: secret must not be empty.");
  return `t=${timestamp},v1=${digest(timestamp, body, secret)}`;
}

/**
 * A canonical timestamp followed by 1–8 lower-case hex `v1` digests, and
 * nothing else.
 *
 * - An unknown field is a header we do not understand, which must fail rather
 *   than be silently ignored.
 * - The timestamp has exactly one spelling (no `0001`, no 13-digit values):
 *   two header strings that verify against the same digest would otherwise
 *   let a replay past a cache keyed on the raw header.
 * - The repetition is bounded so an enormous header cannot make us hash and
 *   compare indefinitely.
 */
const HEADER_RE = /^t=(0|[1-9]\d{0,11})((?:,v1=[a-f0-9]{64}){1,8})$/;

export function verifyWebhookSignature(
  body: string,
  header: string,
  secret: string,
  opts: { now?: number; toleranceSeconds?: number } = {},
): boolean {
  // `createHmac("sha256", "")` is legal in Node, so an unset
  // `process.env.WEBHOOK_SECRET ?? ""` would happily verify anything an
  // attacker signed with the empty key. Refuse before we ever hash.
  if (!secret) return false;
  // A repeated HTTP header arrives as an array in several frameworks, and
  // `["t=1", "v1=<hex>"]` stringifies straight into a well-formed header.
  if (typeof header !== "string") return false;
  const m = HEADER_RE.exec(header);
  if (!m) return false;
  const t = Number(m[1]);
  const now = opts.now ?? Math.floor(Date.now() / 1000);
  if (
    Math.abs(now - t) > (opts.toleranceSeconds ?? SIGNATURE_TOLERANCE_SECONDS)
  )
    return false;
  const expected = Buffer.from(digest(t, body, secret), "hex");
  // Any matching `v1` is enough — during a secret rotation the sender emits
  // one digest per live key, and an SDK pinned in a user's deployed app has
  // to keep verifying both.
  for (const field of m[2]!.split(",").slice(1)) {
    const actual = Buffer.from(field.slice("v1=".length), "hex");
    if (actual.length === expected.length && timingSafeEqual(actual, expected))
      return true;
  }
  return false;
}
