/**
 * Vendors the icons this app uses out of Iconify's Lucide collection.
 *
 * `bun run icons` rewrites `src/components/ui/icon-data.ts`, which is
 * committed. Nothing fetches an icon at runtime: `@iconify/react` and the
 * Iconify API would both put a network request (and a CSP entry) between a
 * self-hosted instance and its own chrome, for artwork that never changes
 * between builds. `@iconify-json/lucide` is a devDependency for the same
 * reason — it is a build input, not a shipped one.
 *
 * Only the `stroke-width` is rewritten. Lucide draws at 2 on a 24 grid; this
 * interface is hairlines and thin type, and 2 reads heavy beside it, so the
 * attribute is dropped from the artwork and the `<svg>` supplies the house
 * weight instead. Everything else is Lucide's own geometry, untouched.
 *
 * To add an icon: put it in MAP, run `bun run icons`, export it from
 * `icons.tsx`. An unknown Lucide name fails here rather than rendering
 * nothing.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "src", "components", "ui", "icon-data.ts");
const SOURCE = join(
  here,
  "..",
  "..",
  "..",
  "node_modules",
  "@iconify-json",
  "lucide",
  "icons.json",
);

/** House name → Lucide name. The house names are what the app imports. */
const MAP: Record<string, string> = {
  // Navigation
  Gauge: "gauge",
  Mail: "mail",
  Globe: "globe",
  Key: "key",
  Webhook: "webhook",
  ShieldOff: "shield-off",
  Template: "layout-template",
  Users: "users",
  Megaphone: "megaphone",
  Settings: "settings",
  Shield: "shield",
  User: "user",
  Book: "book-open",
  CreditCard: "credit-card",
  Building: "building-2",
  Cloud: "cloud",
  Server: "server",
  // Direction
  ChevronDown: "chevron-down",
  ChevronUp: "chevron-up",
  ChevronRight: "chevron-right",
  ChevronLeft: "chevron-left",
  ArrowLeft: "arrow-left",
  ArrowRight: "arrow-right",
  ArrowUp: "arrow-up",
  ArrowDown: "arrow-down",
  External: "external-link",
  Refresh: "refresh-cw",
  // Actions
  Plus: "plus",
  Minus: "minus",
  X: "x",
  Check: "check",
  Trash: "trash-2",
  Copy: "copy",
  Pencil: "pencil",
  Search: "search",
  Send: "send",
  Eye: "eye",
  Download: "download",
  Upload: "upload",
  Filter: "list-filter",
  Grip: "grip-vertical",
  More: "ellipsis",
  LogOut: "log-out",
  Link: "link",
  // Status
  Alert: "triangle-alert",
  Info: "info",
  CheckCircle: "circle-check",
  Clock: "clock",
  Calendar: "calendar",
  Sparkle: "sparkles",
  // Editor blocks
  Heading: "heading",
  Text: "type",
  ButtonBlock: "square-mouse-pointer",
  Image: "image",
  Divider: "separator-horizontal",
  Spacer: "stretch-vertical",
  Columns: "columns-3",
  Bold: "bold",
  Italic: "italic",
  Menu: "menu",
  AlignLeft: "align-left",
  AlignCenter: "align-center",
  AlignRight: "align-right",
};

interface Collection {
  icons: Record<string, { body: string; width?: number; height?: number }>;
  aliases?: Record<string, { parent: string }>;
  width?: number;
  height?: number;
}

const collection = JSON.parse(readFileSync(SOURCE, "utf8")) as Collection;

function resolve(name: string) {
  const direct = collection.icons[name];
  if (direct) return direct;
  const alias = collection.aliases?.[name];
  const target = alias && collection.icons[alias.parent];
  if (target) return target;
  throw new Error(`lucide has no icon "${name}"`);
}

const lines: string[] = [];
for (const [house, lucide] of Object.entries(MAP)) {
  const { body, width, height } = resolve(lucide);
  // The grid has to be the one the `<svg>` declares, or the artwork is
  // cropped. Every Lucide icon is 24×24; anything else is a mistake worth
  // hearing about rather than rendering wrong.
  const w = width ?? collection.width ?? 24;
  const h = height ?? collection.height ?? 24;
  if (w !== 24 || h !== 24)
    throw new Error(
      `${lucide} is ${w}×${h}, not the 24 grid the renderer uses`,
    );
  const stripped = body.replaceAll(' stroke-width="2"', "");
  lines.push(`  /** lucide: ${lucide} */`);
  lines.push(`  ${house}: ${JSON.stringify(stripped)},`);
}

const file = `/**
 * Generated by \`bun run icons\` from @iconify-json/lucide. Do not edit.
 *
 * Each value is the inner markup of a 24×24 icon, with Lucide's
 * \`stroke-width="2"\` removed so the \`<svg>\` in \`icons.tsx\` can set the
 * house weight. See \`scripts/build-icons.ts\`.
 */
export const ICON_BODIES = {
${lines.join("\n")}
} as const;

export type IconName = keyof typeof ICON_BODIES;
`;

// Formatted here rather than left to whoever notices. `bun run format:check`
// gates CI, and a generator whose output fails it turns "add an icon" into a
// red build for a reason that has nothing to do with the icon.
const pretty = await format(file, {
  ...(await resolveConfig(OUT)),
  filepath: OUT,
});
writeFileSync(OUT, pretty, "utf8");
console.log(`icon-data.ts: ${Object.keys(MAP).length} icons from lucide`);
