/**
 * Generated by `bun run icons` from @iconify-json/lucide. Do not edit.
 *
 * Each value is the inner markup of a 24×24 icon, with Lucide's
 * `stroke-width="2"` removed so the `<svg>` in `icons.tsx` can set the
 * house weight. See `scripts/build-icons.ts`.
 */
export const ICON_BODIES = {
  /** lucide: gauge */
  Gauge:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m12 14l4-4M3.34 19a10 10 0 1 1 17.32 0"/>',
  /** lucide: mail */
  Mail: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="m22 7l-8.991 5.727a2 2 0 0 1-2.009 0L2 7"/><rect width="20" height="16" x="2" y="4" rx="2"/></g>',
  /** lucide: globe */
  Globe:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20a14.5 14.5 0 0 0 0-20M2 12h20"/></g>',
  /** lucide: key */
  Key: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="m15.5 7.5l2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4m2-2l-9.6 9.6"/><circle cx="7.5" cy="15.5" r="5.5"/></g>',
  /** lucide: webhook */
  Webhook:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M18 16.98h-5.99c-1.1 0-1.95.94-2.48 1.9A4 4 0 0 1 2 17c.01-.7.2-1.4.57-2"/><path d="m6 17l3.13-5.78c.53-.97.1-2.18-.5-3.1a4 4 0 1 1 6.89-4.06"/><path d="m12 6l3.13 5.73C15.66 12.7 16.9 13 18 13a4 4 0 0 1 0 8"/></g>',
  /** lucide: shield-off */
  ShieldOff:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m2 2l20 20M5 5a1 1 0 0 0-1 1v7c0 5 3.5 7.5 7.67 8.94a1 1 0 0 0 .67.01c2.35-.82 4.48-1.97 5.9-3.71M9.309 3.652A12.3 12.3 0 0 0 11.24 2.28a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1v7a10 10 0 0 1-.08 1.264"/>',
  /** lucide: layout-template */
  Template:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="7" x="3" y="3" rx="1"/><rect width="9" height="7" x="3" y="14" rx="1"/><rect width="5" height="7" x="16" y="14" rx="1"/></g>',
  /** lucide: users */
  Users:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M16 3.128a4 4 0 0 1 0 7.744M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/></g>',
  /** lucide: megaphone */
  Megaphone:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M11 6a13 13 0 0 0 8.4-2.8A1 1 0 0 1 21 4v12a1 1 0 0 1-1.6.8A13 13 0 0 0 11 14H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z"/><path d="M6 14a12 12 0 0 0 2.4 7.2a2 2 0 0 0 3.2-2.4A8 8 0 0 1 10 14M8 6v8"/></g>',
  /** lucide: settings */
  Settings:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0a2.34 2.34 0 0 0 3.319 1.915a2.34 2.34 0 0 1 2.33 4.033a2.34 2.34 0 0 0 0 3.831a2.34 2.34 0 0 1-2.33 4.033a2.34 2.34 0 0 0-3.319 1.915a2.34 2.34 0 0 1-4.659 0a2.34 2.34 0 0 0-3.32-1.915a2.34 2.34 0 0 1-2.33-4.033a2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"/><circle cx="12" cy="12" r="3"/></g>',
  /** lucide: shield */
  Shield:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/>',
  /** lucide: user */
  User: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></g>',
  /** lucide: book-open */
  Book: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 5v16m8.001-2A2 2 0 0 0 22 17V5a2 2 0 0 0-1.999-2L16 3.002A5 5 0 0 0 12 5a5 5 0 0 0-4-2H4a2 2 0 0 0-2 2v12a2 2 0 0 0 1.999 2H8a5 5 0 0 1 4 2a5 5 0 0 1 4-2z"/>',
  /** lucide: credit-card */
  CreditCard:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="14" x="2" y="5" rx="2"/><path d="M2 10h20"/></g>',
  /** lucide: building-2 */
  Building:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M10 12h4m-4-4h4m0 13v-3a2 2 0 0 0-4 0v3"/><path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"/><path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"/></g>',
  /** lucide: cloud */
  Cloud:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9"/>',
  /** lucide: server */
  Server:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="8" x="2" y="2" rx="2" ry="2"/><rect width="20" height="8" x="2" y="14" rx="2" ry="2"/><path d="M6 6h.01M6 18h.01"/></g>',
  /** lucide: chevron-down */
  ChevronDown:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m6 9l6 6l6-6"/>',
  /** lucide: chevron-up */
  ChevronUp:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m18 15l-6-6l-6 6"/>',
  /** lucide: chevron-right */
  ChevronRight:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m9 18l6-6l-6-6"/>',
  /** lucide: chevron-left */
  ChevronLeft:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m15 18l-6-6l6-6"/>',
  /** lucide: arrow-left */
  ArrowLeft:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m12 19l-7-7l7-7m7 7H5"/>',
  /** lucide: arrow-right */
  ArrowRight:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M5 12h14m-7-7l7 7l-7 7"/>',
  /** lucide: arrow-up */
  ArrowUp:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m5 12l7-7l7 7m-7 7V5"/>',
  /** lucide: arrow-down */
  ArrowDown:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 5v14m7-7l-7 7l-7-7"/>',
  /** lucide: external-link */
  External:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 3h6v6m-11 5L21 3m-3 10v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>',
  /** lucide: refresh-cw */
  Refresh:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12a9 9 0 0 1 9-9a9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5m5 4a9 9 0 0 1-9 9a9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/></g>',
  /** lucide: plus */
  Plus: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M5 12h14m-7-7v14"/>',
  /** lucide: minus */
  Minus:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M5 12h14"/>',
  /** lucide: x */
  X: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M18 6L6 18M6 6l12 12"/>',
  /** lucide: check */
  Check:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M20 6L9 17l-5-5"/>',
  /** lucide: trash-2 */
  Trash:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M10 11v6m4-6v6m5-11v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6M3 6h18M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',
  /** lucide: copy */
  Copy: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></g>',
  /** lucide: pencil */
  Pencil:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497zM15 5l4 4"/>',
  /** lucide: search */
  Search:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="m21 21l-4.34-4.34"/><circle cx="11" cy="11" r="8"/></g>',
  /** lucide: send */
  Send: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11zm7.318-19.539l-10.94 10.939"/>',
  /** lucide: eye */
  Eye: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M2.062 12.348a1 1 0 0 1 0-.696a10.75 10.75 0 0 1 19.876 0a1 1 0 0 1 0 .696a10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/></g>',
  /** lucide: download */
  Download:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M12 15V3m9 12v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10l5 5l5-5"/></g>',
  /** lucide: upload */
  Upload:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 3v12m5-7l-5-5l-5 5m14 7v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>',
  /** lucide: list-filter */
  Filter:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M2 5h20M6 12h12m-9 7h6"/>',
  /** lucide: grip-vertical */
  Grip: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="12" r="1"/><circle cx="9" cy="5" r="1"/><circle cx="9" cy="19" r="1"/><circle cx="15" cy="12" r="1"/><circle cx="15" cy="5" r="1"/><circle cx="15" cy="19" r="1"/></g>',
  /** lucide: ellipsis */
  More: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/></g>',
  /** lucide: log-out */
  LogOut:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m16 17l5-5l-5-5m5 5H9m0 9H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>',
  /** lucide: link */
  Link: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></g>',
  /** lucide: triangle-alert */
  Alert:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m21.73 18l-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3M12 9v4m0 4h.01"/>',
  /** lucide: info */
  Info: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4m0-4h.01"/></g>',
  /** lucide: circle-check */
  CheckCircle:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="m9 12l2 2l4-4"/></g>',
  /** lucide: clock */
  Clock:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></g>',
  /** lucide: calendar */
  Calendar:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M8 2v3m8-3v3"/><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M3 9h18"/></g>',
  /** lucide: sparkles */
  Sparkle:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594zM20 2v4m2-2h-4"/><circle cx="4" cy="20" r="2"/></g>',
  /** lucide: heading */
  Heading:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 12h12M6 20V4m12 16V4"/>',
  /** lucide: type */
  Text: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M12 4v16M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2M9 20h6"/>',
  /** lucide: square-mouse-pointer */
  ButtonBlock:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M12.034 12.681a.498.498 0 0 1 .647-.647l9 3.5a.5.5 0 0 1-.033.943l-3.444 1.068a1 1 0 0 0-.66.66l-1.067 3.443a.5.5 0 0 1-.943.033z"/><path d="M21 11V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h6"/></g>',
  /** lucide: image */
  Image:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15l-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/></g>',
  /** lucide: separator-horizontal */
  Divider:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m16 16l-4 4l-4-4m-5-4h18M8 8l4-4l4 4"/>',
  /** lucide: stretch-vertical */
  Spacer:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><rect width="6" height="20" x="4" y="2" rx="2"/><rect width="6" height="20" x="14" y="2" rx="2"/></g>',
  /** lucide: columns-3 */
  Columns:
    '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M9 3v18m6-18v18"/></g>',
  /** lucide: bold */
  Bold: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8"/>',
  /** lucide: italic */
  Italic:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M19 4h-9m4 16H5M15 4L9 20"/>',
  /** lucide: menu */
  Menu: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M4 5h16M4 12h16M4 19h16"/>',
  /** lucide: align-left */
  AlignLeft:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M15 12H3m14 6H3M21 6H3"/>',
  /** lucide: align-center */
  AlignCenter:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M17 12H7m12 6H5M21 6H3"/>',
  /** lucide: align-right */
  AlignRight:
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M21 12H9m12 6H7M21 6H3"/>',
} as const;

export type IconName = keyof typeof ICON_BODIES;
