/* GENERATED pixel-art brand marks — see scripts/gen-brand.mjs.
 * Every coordinate is a whole unit on the source grid (20x15 for the mark,
 * 52x9 for the wordmark), so the art stays crisp at any size.
 * Edit the generator and re-run it; do not edit this file. */

type SvgProps = React.SVGProps<SVGSVGElement>;

const CRISP = { shapeRendering: "crispEdges" } as const;

/** The mark: an envelope in two-pixel line. `mono` inherits the current
 * colour instead of carrying the indigo ramp. */
export function Mark({
  size = 24,
  mono = false,
  ...rest
}: SvgProps & { size?: number; mono?: boolean }) {
  return (
    <svg
      viewBox="0 0 20 15"
      height={size}
      width={(size * 20) / 15}
      fill="none"
      style={CRISP}
      aria-hidden
      {...rest}
    >
      {mono ? (
        <>
          <path
            fill="currentColor"
            d="M1 1h2v1h-2zM17 1h2v1h-2zM1 2h4v1h-4zM15 2h4v1h-4zM1 3h5v1h-5zM6 3h1v1h-1zM13 3h6v1h-6zM1 4h2v1h-2zM5 4h4v1h-4zM11 4h1v1h-1zM12 4h3v1h-3zM17 4h2v1h-2zM1 5h2v1h-2zM7 5h3v1h-3zM10 5h3v1h-3zM17 5h1v1h-1zM18 5h1v1h-1zM1 6h1v1h-1zM2 6h1v1h-1zM9 6h2v1h-2zM17 6h2v1h-2zM1 7h2v1h-2zM17 7h2v1h-2zM1 8h2v1h-2zM17 8h2v1h-2zM1 9h2v1h-2zM17 9h2v1h-2zM1 10h2v1h-2zM17 10h1v1h-1zM18 10h1v1h-1zM1 11h1v1h-1zM2 11h1v1h-1zM17 11h2v1h-2zM1 12h7v1h-7zM8 12h7v1h-7zM15 12h4v1h-4zM1 13h5v1h-5zM6 13h8v1h-8zM14 13h5v1h-5z"
          />
        </>
      ) : (
        <>
          <path
            fill="#c7d2fe"
            d="M1 1h2v1h-2zM1 2h4v1h-4zM1 3h5v1h-5zM1 4h2v1h-2zM1 5h2v1h-2zM1 6h1v1h-1z"
          />
          <path
            fill="#818cf8"
            d="M17 1h2v1h-2zM15 2h4v1h-4zM13 3h6v1h-6zM12 4h3v1h-3zM17 4h2v1h-2zM10 5h3v1h-3zM17 5h1v1h-1zM9 6h2v1h-2zM2 11h1v1h-1zM1 12h7v1h-7zM1 13h5v1h-5z"
          />
          <path
            fill="#a5b4fc"
            d="M6 3h1v1h-1zM5 4h4v1h-4zM11 4h1v1h-1zM7 5h3v1h-3zM2 6h1v1h-1zM1 7h2v1h-2zM1 8h2v1h-2zM1 9h2v1h-2zM1 10h2v1h-2zM1 11h1v1h-1z"
          />
          <path
            fill="#6366f1"
            d="M18 5h1v1h-1zM17 6h2v1h-2zM17 7h2v1h-2zM17 8h2v1h-2zM17 9h2v1h-2zM17 10h1v1h-1zM8 12h7v1h-7zM6 13h8v1h-8z"
          />
          <path
            fill="#4f46e5"
            d="M18 10h1v1h-1zM17 11h2v1h-2zM15 12h4v1h-4zM14 13h5v1h-5z"
          />
        </>
      )}
    </svg>
  );
}

/** Same envelope on an ink tile — avatars, favicons, tight nav slots. */
export function MarkTile({ size = 24, ...rest }: SvgProps & { size?: number }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      style={CRISP}
      aria-hidden
      {...rest}
    >
      <rect width="24" height="24" rx="5.5" fill="#0a0a0a" />
      <path
        fill="#c7d2fe"
        d="M3 6h2v1h-2zM3 7h4v1h-4zM3 8h5v1h-5zM3 9h2v1h-2zM3 10h2v1h-2zM3 11h1v1h-1z"
      />
      <path
        fill="#818cf8"
        d="M19 6h2v1h-2zM17 7h4v1h-4zM15 8h6v1h-6zM14 9h3v1h-3zM19 9h2v1h-2zM12 10h3v1h-3zM19 10h1v1h-1zM11 11h2v1h-2zM4 16h1v1h-1zM3 17h7v1h-7zM3 18h5v1h-5z"
      />
      <path
        fill="#a5b4fc"
        d="M8 8h1v1h-1zM7 9h4v1h-4zM13 9h1v1h-1zM9 10h3v1h-3zM4 11h1v1h-1zM3 12h2v1h-2zM3 13h2v1h-2zM3 14h2v1h-2zM3 15h2v1h-2zM3 16h1v1h-1z"
      />
      <path
        fill="#6366f1"
        d="M20 10h1v1h-1zM19 11h2v1h-2zM19 12h2v1h-2zM19 13h2v1h-2zM19 14h2v1h-2zM19 15h1v1h-1zM10 17h7v1h-7zM8 18h8v1h-8z"
      />
      <path
        fill="#4f46e5"
        d="M20 15h1v1h-1zM19 16h2v1h-2zM17 17h4v1h-4zM16 18h5v1h-5z"
      />
    </svg>
  );
}

/** "Sendsprite" in the pixel face. `mono` inherits the current colour. */
export function Wordmark({
  height = 18,
  mono = false,
  ...rest
}: SvgProps & { height?: number; mono?: boolean }) {
  return (
    <svg
      viewBox="0 0 52 9"
      height={height}
      width={(height * 52) / 9}
      fill="none"
      style={CRISP}
      role="img"
      aria-label="Sendsprite"
      {...rest}
    >
      {mono ? (
        <>
          <path
            fill="currentColor"
            d="M1 0h4v1h-4zM22 0h1v1h-1zM44 0h1v1h-1zM0 1h1v1h-1zM22 1h1v1h-1zM41 1h1v1h-1zM44 1h1v1h-1zM0 2h1v1h-1zM7 2h3v1h-3zM12 2h1v1h-1zM14 2h2v1h-2zM19 2h4v1h-4zM25 2h4v1h-4zM30 2h4v1h-4zM36 2h1v1h-1zM38 2h2v1h-2zM43 2h3v1h-3zM48 2h3v1h-3zM1 3h3v1h-3zM6 3h1v1h-1zM10 3h1v1h-1zM12 3h2v1h-2zM16 3h1v1h-1zM18 3h1v1h-1zM22 3h1v1h-1zM24 3h1v1h-1zM30 3h1v1h-1zM34 3h1v1h-1zM36 3h2v1h-2zM41 3h1v1h-1zM44 3h1v1h-1zM47 3h1v1h-1zM51 3h1v1h-1zM4 4h1v1h-1zM6 4h5v1h-5zM12 4h1v1h-1zM16 4h1v1h-1zM18 4h1v1h-1zM22 4h1v1h-1zM25 4h3v1h-3zM30 4h1v1h-1zM34 4h1v1h-1zM36 4h1v1h-1zM41 4h1v1h-1zM44 4h1v1h-1zM47 4h5v1h-5zM4 5h1v1h-1zM6 5h1v1h-1zM12 5h1v1h-1zM16 5h1v1h-1zM18 5h1v1h-1zM22 5h1v1h-1zM28 5h1v1h-1zM30 5h1v1h-1zM34 5h1v1h-1zM36 5h1v1h-1zM41 5h1v1h-1zM44 5h1v1h-1zM47 5h1v1h-1zM0 6h4v1h-4zM7 6h3v1h-3zM12 6h1v1h-1zM16 6h1v1h-1zM19 6h4v1h-4zM24 6h4v1h-4zM30 6h4v1h-4zM36 6h1v1h-1zM41 6h1v1h-1zM44 6h2v1h-2zM48 6h3v1h-3zM30 7h1v1h-1zM30 8h1v1h-1z"
          />
        </>
      ) : (
        <>
          <path
            fill="#ffffff"
            d="M1 0h4v1h-4zM22 0h1v1h-1zM44 0h1v1h-1zM0 1h1v1h-1zM22 1h1v1h-1zM41 1h1v1h-1zM44 1h1v1h-1zM0 2h1v1h-1zM7 2h3v1h-3zM12 2h1v1h-1zM14 2h2v1h-2zM19 2h4v1h-4zM25 2h4v1h-4zM30 2h4v1h-4zM36 2h1v1h-1zM38 2h2v1h-2zM43 2h3v1h-3zM48 2h3v1h-3zM1 3h3v1h-3zM6 3h1v1h-1zM10 3h1v1h-1zM12 3h2v1h-2zM16 3h1v1h-1zM18 3h1v1h-1zM22 3h1v1h-1zM24 3h1v1h-1zM30 3h1v1h-1zM34 3h1v1h-1zM36 3h2v1h-2zM41 3h1v1h-1zM44 3h1v1h-1zM47 3h1v1h-1zM51 3h1v1h-1zM4 4h1v1h-1zM6 4h5v1h-5zM12 4h1v1h-1zM16 4h1v1h-1zM18 4h1v1h-1zM22 4h1v1h-1zM25 4h3v1h-3zM30 4h1v1h-1zM34 4h1v1h-1zM36 4h1v1h-1zM41 4h1v1h-1zM44 4h1v1h-1zM47 4h5v1h-5zM4 5h1v1h-1zM6 5h1v1h-1zM12 5h1v1h-1zM16 5h1v1h-1zM18 5h1v1h-1zM22 5h1v1h-1zM28 5h1v1h-1zM30 5h1v1h-1zM34 5h1v1h-1zM36 5h1v1h-1zM41 5h1v1h-1zM44 5h1v1h-1zM47 5h1v1h-1zM0 6h4v1h-4zM7 6h3v1h-3zM12 6h1v1h-1zM16 6h1v1h-1zM19 6h4v1h-4zM24 6h4v1h-4zM30 6h4v1h-4zM36 6h1v1h-1zM41 6h1v1h-1zM44 6h2v1h-2zM48 6h3v1h-3zM30 7h1v1h-1zM30 8h1v1h-1z"
          />
        </>
      )}
    </svg>
  );
}

/** Mark + wordmark, optically aligned. The default brand lockup. */
export function Logo({ height = 26, ...rest }: SvgProps & { height?: number }) {
  return (
    <svg
      viewBox="0 0 76 15"
      height={height}
      width={(height * 76) / 15}
      fill="none"
      style={CRISP}
      role="img"
      aria-label="Sendsprite"
      {...rest}
    >
      <path
        fill="#c7d2fe"
        d="M1 1h2v1h-2zM1 2h4v1h-4zM1 3h5v1h-5zM1 4h2v1h-2zM1 5h2v1h-2zM1 6h1v1h-1z"
      />
      <path
        fill="#818cf8"
        d="M17 1h2v1h-2zM15 2h4v1h-4zM13 3h6v1h-6zM12 4h3v1h-3zM17 4h2v1h-2zM10 5h3v1h-3zM17 5h1v1h-1zM9 6h2v1h-2zM2 11h1v1h-1zM1 12h7v1h-7zM1 13h5v1h-5z"
      />
      <path
        fill="#a5b4fc"
        d="M6 3h1v1h-1zM5 4h4v1h-4zM11 4h1v1h-1zM7 5h3v1h-3zM2 6h1v1h-1zM1 7h2v1h-2zM1 8h2v1h-2zM1 9h2v1h-2zM1 10h2v1h-2zM1 11h1v1h-1z"
      />
      <path
        fill="#6366f1"
        d="M18 5h1v1h-1zM17 6h2v1h-2zM17 7h2v1h-2zM17 8h2v1h-2zM17 9h2v1h-2zM17 10h1v1h-1zM8 12h7v1h-7zM6 13h8v1h-8z"
      />
      <path
        fill="#4f46e5"
        d="M18 10h1v1h-1zM17 11h2v1h-2zM15 12h4v1h-4zM14 13h5v1h-5z"
      />
      <g transform="translate(24 4)">
        <path
          fill="#ffffff"
          d="M1 0h4v1h-4zM22 0h1v1h-1zM44 0h1v1h-1zM0 1h1v1h-1zM22 1h1v1h-1zM41 1h1v1h-1zM44 1h1v1h-1zM0 2h1v1h-1zM7 2h3v1h-3zM12 2h1v1h-1zM14 2h2v1h-2zM19 2h4v1h-4zM25 2h4v1h-4zM30 2h4v1h-4zM36 2h1v1h-1zM38 2h2v1h-2zM43 2h3v1h-3zM48 2h3v1h-3zM1 3h3v1h-3zM6 3h1v1h-1zM10 3h1v1h-1zM12 3h2v1h-2zM16 3h1v1h-1zM18 3h1v1h-1zM22 3h1v1h-1zM24 3h1v1h-1zM30 3h1v1h-1zM34 3h1v1h-1zM36 3h2v1h-2zM41 3h1v1h-1zM44 3h1v1h-1zM47 3h1v1h-1zM51 3h1v1h-1zM4 4h1v1h-1zM6 4h5v1h-5zM12 4h1v1h-1zM16 4h1v1h-1zM18 4h1v1h-1zM22 4h1v1h-1zM25 4h3v1h-3zM30 4h1v1h-1zM34 4h1v1h-1zM36 4h1v1h-1zM41 4h1v1h-1zM44 4h1v1h-1zM47 4h5v1h-5zM4 5h1v1h-1zM6 5h1v1h-1zM12 5h1v1h-1zM16 5h1v1h-1zM18 5h1v1h-1zM22 5h1v1h-1zM28 5h1v1h-1zM30 5h1v1h-1zM34 5h1v1h-1zM36 5h1v1h-1zM41 5h1v1h-1zM44 5h1v1h-1zM47 5h1v1h-1zM0 6h4v1h-4zM7 6h3v1h-3zM12 6h1v1h-1zM16 6h1v1h-1zM19 6h4v1h-4zM24 6h4v1h-4zM30 6h4v1h-4zM36 6h1v1h-1zM41 6h1v1h-1zM44 6h2v1h-2zM48 6h3v1h-3zM30 7h1v1h-1zM30 8h1v1h-1z"
        />
      </g>
    </svg>
  );
}
